package com.vioside.foundation.models

enum class InitialCheck {
    DEVICE_ROOT_CHECK_ASYNC,
    NETWORK_AVAILABILITY_CHECK_ASYNC,
    INITIALIZE_THIRD_PARTIES_ASYNC,
    LOADS_REMOTE_CONFIG_ASYNC,
    APP_UPDATE_CHECK_ASYNC,
    BACKEND_AVAILABILITY_CHECK_ASYNC,
    LOAD_OPENID_CONFIGURATION_ASYNC
}